base_url = "https://zentro.codes"
compile_sass = false
build_search_index = false
theme = "zephyr"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
list_pages = false
display_author = true
twitter_card = true
default_theme = "dark"
author = "Rafael Galvan"
favicon = "favicon-16x16.png"

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/projects", name_en = "/projects/" },
  { url = "/hardware", name_en = "/hardware/" },
  { url = "/software", name_en = "/software/" },
  { url = "/blog", name_en = "/blog/" }
]

footer_content_license = "Creative Commons Attribution 4.0 International"
footer_content_link = "https://creativecommons.org/license/by/4.0"
