base_url = "https://zentro.codes"
compile_sass = false
build_search_index = false
theme = "anemone"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
list_pages = false
display_author = true
twitter_card = true
default_theme = "dark"
author = "Rafael Galvan"

header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/projects", name_en = "/projects/" },
  { url = "/hardware", name_en = "/hardware/" },
  { url = "/blog", name_en = "/blog/" }
]
